### ISSUE TITLE
bug report of the phenotype

### ISSUE THREAD

**Issue by gourdchen** [Mwizakunda/fMRI-site-adaptation#1]
it is may be an error, will it affect the result?

in preprocess_data.py

def phenotype_ft_vector(pheno_ft, num_subjects, params):
    gender = pheno_ft[:,0]
    if params['model'] == 'MIDA':
        **eye = pheno_ft[:, 0]**

**Comment by kundaMwiza** [comment]
@gourdchen 

`eye pheno_ft[:, 0]` is just a placeholder when using MIDA based models. Since eye status at scan is a site specific feature, it is ommited from the phenotype features used. 

See lines 227 onwards:
` if params['model'] == 'MIDA':
        phenotype_ft = np.concatenate([phenotype_ft, phenotype_ft_hand], axis=1)
    else:
        phenotype_ft = np.concatenate([phenotype_ft, phenotype_ft_hand, phenotype_ft_eye], axis=1)
`

**Comment by gourdchen** [comment]
oh, I got it. 
And it will calculation the TPE mat data everytime, is it because the data matrix will be different for each loop?
