### ISSUE TITLE
A code comprehension problem

### ISSUE THREAD

**Issue by LeSoleilGo** [Mwizakunda/fMRI-site-adaptation#11]
Hi, I am in trouble with your code. There are two questions.
1: 

> if connectivity in ["correlation", 'partial correlation', 'covariance', 'tangent', "TPE"]:
>         reader.subject_connectivity(time_series, atlas, connectivity, save=True, out_path=cfg.OUTPUT.OUT_PATH)

Could you tell me what 'partial correlation' and 'covariance' are used for? Corresponds to which part in the experiment?
2:
 

>  if params['ensemble']:
>             train.leave_one_site_out_ensemble(params, subject_ids, features, y_data, y, phenotype_ft, pheno_ft)
>         else:
>             train.leave_one_site_out(params, subject_ids, features, y_data, y, phenotype_ft, pheno_ft)

I could not understand the 'ensemble' function. What role does it play in the experimental part?
Thank you. Sorry to bother you so many times.

**Comment by shuo-zhou** [comment]
Hi, our implementation support all types of connectivity in the [Nilearn API](https://nilearn.github.io/dev/modules/generated/nilearn.connectome.ConnectivityMeasure.html#nilearn.connectome.ConnectivityMeasure). For experiments in our paper, we used `correlation`, `tangent`, and `TPE`. If you are interested in the other types of connectivity, Section 2 of [this paper](https://www.sciencedirect.com/science/article/pii/S1053811920300914) should be helpful.

For ensemble, three classifiers are trained on `correlation`, `tangent`, and `TPE` features, separately. Then the prediction will be determined by fusing the outputs of these classifiers. This is a different way of leveraging the data, but not involved in the experiments reported in the TMI paper.

**Comment by LeSoleilGo** [comment]
Thank you very much.
