### ISSUE TITLE
python fetch_data.py is requiring the arguments the location of config file but don't accept

### ISSUE THREAD

**Issue by SaqibMamoon** [Mwizakunda/fMRI-site-adaptation#5]
Hi, I have been trying to run the code, however, I am unable to runt the file fetch_data.py properly. I gave the location of the config file as it requires path to the config file, and I don't what else to do. 

if don't give any argument it raise the error: 
 usage: fetch_data.py [-h] --cfg CFG fetch_data.py: error: the following arguments are required: --cfg
 
 if I give the argument it raise the error of "IsADirectoryError: [Errno 21] Is a directory: "
 
 Please guide how to run the it. what I'm missing.

**Comment by shuo-zhou** [comment]
Hello, thank you for raising this issue. Could you please try again by following the latest instructions in README and let us know if there are any further questions?

**Comment by SaqibMamoon** [comment]
> 

Thank you! it's working now.

**Comment by shuo-zhou** [comment]
> 

Thank you for letting us know. 

Issue fixed by PR #6
