### ISSUE TITLE
An running error

### ISSUE THREAD

**Issue by LeSoleilGo** [Mwizakunda/fMRI-site-adaptation#7]
Hi, When I run python fetch_data.py --cfg configs/download_abide.yaml, There is no corresponding content in folder 50002 and an error is reported:
```
 File "fetch_data.py", line 79, in main
    time_series = reader.get_timeseries(subject_ids, atlas, data_folder)
  File "fMRI-site-adaptation-master\imports\preprocess_data.py", line 88, in get_timeseries
    subject_folder = os.path.join(data_path, subject_list[i])
  File "anaconda3\envs\testFMRI\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "anaconda3\envs\testFMRI\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int64'
```
how can i solve this problem？Thank you。

**Comment by SunANDMx** [comment]
It seems that because there are only 1111 patient information, but 1113 folders are created, resulting in 50002 folders with no content. But how to solve this problem?

**Comment by LeSoleilGo** [comment]
Hello, after I downloaded it, I found that there are only 1035 pieces of data, while there are 1112 pieces of data in Phenotypic_V1_0b_preprocessed1.csv. Is this because the data is not corresponding? Is it enough to just update the Phenotypic_V1_0b_preprocessed1.csv data table? So how do you get the form Phenotypic_V1_0b_preprocessed1.csv?

**Comment by shuo-zhou** [comment]
Hello, 1112 are all subjects but not all data are available after pre-processing. 1035 is the number of all samples available for download according to our default configuration for pre-processing, e.g. `pipeline=cpac` and `atlas=cc200` (please see [the source code](https://github.com/kundaMwiza/fMRI-site-adaptation/blob/9f833edc2aadbe4080a9f79e50222448168f747b/fetch_data.py#L48) for more details, where we use an [API in nilearn](https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_abide_pcp.html)). You may get more or fewer samples if you change the configuration for downloading.

**Comment by LeSoleilGo** [comment]
I have successfully resolved the error. Thank you very much.
