### ISSUE TITLE
Data .1D

### ISSUE THREAD

**Issue by LeSoleilGo** [Mwizakunda/fMRI-site-adaptation#8]
Hi, could you tell me what the number of rows of data at the end of .1D stands for? I've spent a really long time on this. Thank you very much.

**Comment by shuo-zhou** [comment]
Hi, each .1D file is the fMRI time series acquired from one subject. If you follow our default setting, i.e. using the cc200 for atlas, there should be 200 time series in each .1D file (one time series for one brain region), but the time points could be different for each subject.

**Comment by LeSoleilGo** [comment]
Thank you.
