### ISSUE TITLE
A TypeError

### ISSUE THREAD

**Issue by LeSoleilGo** [Mwizakunda/fMRI-site-adaptation#9]
hello，`x_data = MIDA.MIDA(x_data, domain_ft, mu=mu, h=h,labels=False)`. Could you tell me the meaning of `labels=false`? It seems that there is no labels parameter in the function MIDA.
`def MIDA(X, D, y=None, kernel="rbf", mu=0.1, gamma_y=0.1, h=1035, augment=False, return_w=False)`

**Comment by shuo-zhou** [comment]
Hi, thank you for pointing this out. The argument `labels` has been renamed as `y` in the `MIDA` function. This issue should be fixed by PR #10. Please update the code and let me know if there are any problems.

**Comment by LeSoleilGo** [comment]
Thank You
